"""Hermetic native-protocol boundary checks; no providers or credentials."""
import json
from pathlib import Path
import socket
import struct
import sys
import tempfile
import threading
from types import SimpleNamespace
import unittest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from quattro_agent.codex_turn_bridge import (
    CONTROL_PLANE_METHODS, EXECUTION_PLANE_METHODS, CodexTurnBridge,
)

THREAD_ID = "0199b724-06b7-7000-8000-000000000001"

BACKEND = '''import json,sys
for line in sys.stdin:
 r=json.loads(line)
 if r.get("method") in {"thread/start","thread/resume","thread/fork"}:
  if r["params"].get("fixtureLifecycleError"):
   print(json.dumps({"id":r["id"],"error":{"code":-32000,"message":"fixture failure"}}),flush=True)
  else:
   ident=r["params"].get("fixtureThreadId") or r["params"].get("threadId") or "0199b724-06b7-7000-8000-000000000001"
   print(json.dumps({"id":r["id"],"result":{"method":r.get("method"),"thread":{"id":ident,"turns":[]}}}),flush=True)
 elif r.get("method")=="turn/start":
  print(json.dumps({"id":r["id"],"result":{"observed":r["params"]}}),flush=True)
  print(json.dumps({"method":"turn/completed","params":{"threadId":r["params"]["threadId"],"turn":{"id":"backend","status":"completed","items":[]}}}),flush=True)
 elif "id" in r:
  print(json.dumps({"id":r["id"],"result":{"method":r.get("method")}}),flush=True)
'''


class Gate:
    def __init__(self, decision="DIRECT", sensitive=False):
        self.decision = decision
        self.sensitive = sensitive
        self.finished = []
        self.calls = []

    def begin(self, thread_id, prompt, frontend, params):
        self.calls.append((thread_id, prompt, frontend))
        return SimpleNamespace(decision=self.decision, sensitive=self.sensitive, turn_id="direct-turn",
                               plan=SimpleNamespace(plan_id="plan-1", reasoning_effort="low",
                                                    target=SimpleNamespace(route="exact/route")))

    def direct(self, turn):
        return "Direct answer"

    def finish(self, turn, **kwargs):
        self.finished.append(kwargs)


class BridgeTests(unittest.TestCase):
    def test_codex_0_157_1_request_inventory_is_exhaustively_classified(self):
        # Compared with ClientRequest.ts generated by the installed command:
        # codex app-server generate-ts --experimental --out <temporary-dir>
        legacy_only = {
            "userInput", "userInputWithAttachments", "sendUserMessage",
            "sendUserTurn", "execOneOffCommand", "initialized",
        }
        request_methods = ((CONTROL_PLANE_METHODS | EXECUTION_PLANE_METHODS)
                           - legacy_only | {"turn/start", "turn/steer", "turn/interrupt"})
        self.assertEqual(len(request_methods), 170)
        self.assertTrue({
            "thread/settings/update", "collaborationMode/list", "thread/search",
            "thread/timeline/list", "project/read", "mcpServer/event/stream/start",
            "fuzzyFileSearch/sessionStart", "server/diagnostics",
        }.issubset(CONTROL_PLANE_METHODS))
        self.assertTrue({
            "turn/settings/update", "thread/compact/start", "thread/realtime/start",
            "thread/shellCommand", "command/exec", "process/spawn",
            "mcpServer/tool/call", "thread/inject_items", "fs/writeFile",
        }.issubset(EXECUTION_PLANE_METHODS))

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.gate = Gate()
        self.bridge = CodexTurnBridge(Path(self.tmp.name) / "bridge.sock",
                                      [sys.executable, "-u", "-c", BACKEND], {}, self.gate)
        self.errors = []
        def run():
            try:
                self.bridge.run()
            except Exception as error:
                self.errors.append(error)
        self.worker = threading.Thread(target=run)
        self.worker.start()
        self.assertTrue(self.bridge.ready.wait(5))
        self.sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        self.sock.settimeout(5)
        self.sock.connect(str(self.bridge.socket_path))
        self.stream = self.sock.makefile("rwb", buffering=0)
        self.stream.write(b"GET /rpc HTTP/1.1\r\nHost: localhost\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Version: 13\r\nSec-WebSocket-Key: MDEyMzQ1Njc4OWFiY2RlZg==\r\n\r\n")
        headers = b""
        while not headers.endswith(b"\r\n\r\n"):
            headers += self.stream.read(1)
        self.assertIn(b"101 Switching Protocols", headers)
        # Most focused turn tests begin after a successful native thread/start.
        self.bridge._current_thread_id = THREAD_ID

    def tearDown(self):
        self.stream.close()
        self.sock.close()
        self.worker.join(7)
        self.assertFalse(self.worker.is_alive())
        self.assertEqual(self.errors, [])
        self.tmp.cleanup()

    def send(self, method, params=None, request_id=1):
        params = dict(params or {})
        if params.get("threadId") == "thread-1":
            params["threadId"] = THREAD_ID
        raw = json.dumps({"id":request_id,"method":method,"params":params}).encode()
        self._send_raw(raw)

    def _send_raw(self, raw):
        header = b"\x81" + (bytes([128 | len(raw)]) if len(raw) < 126 else b"\xfe" + struct.pack("!H", len(raw)))
        self.stream.write(header + b"mask" + bytes(b ^ b"mask"[i % 4] for i, b in enumerate(raw)))

    def receive(self):
        header = self.stream.read(2)
        size = header[1] & 127
        if size == 126:
            size = struct.unpack("!H", self.stream.read(2))[0]
        elif size == 127:
            size = struct.unpack("!Q", self.stream.read(8))[0]
        data = b""
        while len(data) < size:
            data += self.stream.read(size - len(data))
        return json.loads(data)

    def test_direct_has_native_events_without_backend_generation(self):
        self.send("turn/start", {"threadId":"thread-1","input":[{"type":"text","text":"Explain recursion"}]})
        messages = []
        while True:
            message = self.receive()
            messages.append(message)
            if message.get("method") == "turn/completed":
                break
        self.assertEqual(messages[0]["result"]["turn"]["id"], "direct-turn")
        self.assertEqual([m.get("method") for m in messages[1:]], [
            "turn/started", "item/started", "item/agentMessage/delta", "item/completed", "turn/completed"])
        self.assertEqual(messages[-1]["params"]["turn"]["status"], "completed")
        self.assertEqual(self.gate.calls, [(THREAD_ID, "Explain recursion", "codex")])

    def test_fresh_thread_response_bootstraps_first_turn_without_frontend_id(self):
        thread_id = "0199b724-06b7-7000-8000-000000000010"
        self.send("thread/start", {"fixtureThreadId":thread_id}, 40)
        self.assertEqual(self.receive()["result"]["thread"]["id"], thread_id)
        self.send("turn/start", {"input":[{"type":"text","text":"First"}]}, 41)
        while self.receive().get("method") != "turn/completed":
            pass
        self.send("turn/start", {"input":[{"type":"text","text":"Second"}]}, 42)
        while self.receive().get("method") != "turn/completed":
            pass
        self.assertEqual(self.gate.calls, [
            (thread_id, "First", "codex"), (thread_id, "Second", "codex"),
        ])

    def test_bootstrapped_first_delegated_turn_is_locked_before_dispatch(self):
        thread_id = "0199b724-06b7-7000-8000-000000000022"
        self.send("thread/start", {"fixtureThreadId":thread_id}, 43)
        self.receive()
        self.gate.decision = "DELEGATE"
        self.send("turn/start", {"input":[{"type":"text","text":"Build"}],
                  "model":"unapproved", "effort":"ultra"}, 44)
        observed = self.receive()["result"]["observed"]
        self.assertEqual(observed["threadId"], thread_id)
        self.assertEqual(observed["model"], "exact/route")
        self.assertEqual(observed["effort"], "low")
        self.assertEqual(observed["responsesapiClientMetadata"]["quattro_plan_id"], "plan-1")
        self.assertEqual(self.receive()["method"], "turn/completed")

    def test_new_thread_rebinds_missing_id_within_same_process(self):
        first = "0199b724-06b7-7000-8000-000000000011"
        second = "0199b724-06b7-7000-8000-000000000012"
        for request_id, thread_id in ((50, first), (51, second)):
            self.send("thread/start", {"fixtureThreadId":thread_id}, request_id)
            self.assertEqual(self.receive()["result"]["thread"]["id"], thread_id)
        self.send("turn/start", {"input":[{"type":"text","text":"New thread"}]}, 52)
        while self.receive().get("method") != "turn/completed":
            pass
        self.assertEqual(self.gate.calls, [(second, "New thread", "codex")])

    def test_resume_binds_only_matching_canonical_thread(self):
        thread_id = "0199b724-06b7-7000-8000-000000000013"
        self.send("thread/resume", {"threadId":thread_id}, 60)
        self.assertEqual(self.receive()["result"]["thread"]["id"], thread_id)
        self.send("turn/start", {"input":[{"type":"text","text":"Resumed"}]}, 61)
        while self.receive().get("method") != "turn/completed":
            pass
        self.assertEqual(self.gate.calls, [(thread_id, "Resumed", "codex")])

    def test_failed_lifecycle_does_not_bind_or_inherit_stale_thread(self):
        self.send("thread/start", {"fixtureLifecycleError":True}, 70)
        self.assertIn("error", self.receive())
        self.send("turn/start", {"input":[{"type":"text","text":"Must fail"}]}, 71)
        self.assertIn("error", self.receive())
        self.assertEqual(self.gate.calls, [])

    def test_native_bindings_are_private_to_each_bridge(self):
        first = "0199b724-06b7-7000-8000-000000000015"
        second = "0199b724-06b7-7000-8000-000000000016"
        other = CodexTurnBridge(Path(self.tmp.name) / "other.sock", [], {}, Gate())
        self.bridge._lifecycle_requests[90] = ("thread/start", None, 0)
        other._lifecycle_requests[90] = ("thread/start", None, 0)
        self.bridge._bind_lifecycle_response(90, {"id":90,"result":{"thread":{"id":first}}})
        other._bind_lifecycle_response(90, {"id":90,"result":{"thread":{"id":second}}})
        self.assertEqual(self.bridge._current_thread_id, first)
        self.assertEqual(other._current_thread_id, second)

    def test_mismatched_resume_response_cannot_replace_binding(self):
        original = "0199b724-06b7-7000-8000-000000000017"
        unrelated = "0199b724-06b7-7000-8000-000000000018"
        self.bridge._lifecycle_requests[91] = ("thread/start", None, 0)
        self.bridge._bind_lifecycle_response(91, {"id":91,"result":{"thread":{"id":original}}})
        self.bridge._lifecycle_requests[92] = ("thread/resume", original, 0)
        self.bridge._bind_lifecycle_response(92, {"id":92,"result":{"thread":{"id":unrelated}}})
        self.assertEqual(self.bridge._current_thread_id, original)

    def test_explicit_id_cannot_bypass_failed_or_mismatched_lifecycle(self):
        old = "0199b724-06b7-7000-8000-000000000023"
        other = "0199b724-06b7-7000-8000-000000000024"
        self.send("thread/start", {"fixtureThreadId":old}, 100)
        self.receive()
        self.send("thread/start", {"fixtureLifecycleError":True}, 101)
        self.assertIn("error", self.receive())
        self.send("turn/start", {"threadId":old,
                  "input":[{"type":"text","text":"Stale"}]}, 102)
        self.assertIn("error", self.receive())
        self.bridge._lifecycle_requests[103] = ("thread/resume", old,
                                                self.bridge._lifecycle_generation)
        self.bridge._bind_lifecycle_response(
            103, {"id":103,"result":{"thread":{"id":other}}},
        )
        self.send("turn/start", {"threadId":old,
                  "input":[{"type":"text","text":"Mismatch"}]}, 104)
        self.assertIn("error", self.receive())
        self.assertEqual(self.gate.calls, [])

    def test_invalid_lifecycle_identity_cannot_authorize_explicit_turn(self):
        self.bridge._current_thread_id = None
        self.bridge._lifecycle_requests[105] = ("thread/start", None,
                                                self.bridge._lifecycle_generation)
        self.bridge._bind_lifecycle_response(
            105, {"id":105,"result":{"thread":{"id":"not-a-canonical-id"}}},
        )
        self.send("turn/start", {"threadId":THREAD_ID,
                  "input":[{"type":"text","text":"Must fail"}]}, 106)
        self.assertIn("error", self.receive())
        self.assertEqual(self.gate.calls, [])

    def test_duplicate_pending_lifecycle_request_id_fails_closed(self):
        messages = []
        bridge = CodexTurnBridge(Path(self.tmp.name) / "duplicate.sock", [], {}, Gate())
        bridge._current_thread_id = THREAD_ID
        bridge._lifecycle_generation = 1
        bridge._lifecycle_requests[107] = ("thread/start", None, 1)
        bridge._send = messages.append
        bridge.handle({"id":107,"method":"thread/start","params":{}})
        self.assertIsNone(bridge._current_thread_id)
        self.assertIn("error", messages[0])

    def test_pending_or_failed_new_thread_cannot_reuse_previous_binding(self):
        original = "0199b724-06b7-7000-8000-000000000019"
        self.send("thread/start", {"fixtureThreadId":original}, 93)
        self.receive()
        self.send("thread/start", {"fixtureLifecycleError":True}, 94)
        self.assertIn("error", self.receive())
        self.send("turn/start", {"input":[{"type":"text","text":"No stale reuse"}]}, 95)
        self.assertIn("error", self.receive())
        self.assertEqual(self.gate.calls, [])

    def test_out_of_order_lifecycle_response_cannot_restore_old_binding(self):
        old = "0199b724-06b7-7000-8000-000000000020"
        new = "0199b724-06b7-7000-8000-000000000021"
        self.bridge._lifecycle_generation = 2
        self.bridge._lifecycle_requests[96] = ("thread/start", None, 1)
        self.bridge._lifecycle_requests[97] = ("thread/start", None, 2)
        self.bridge._bind_lifecycle_response(97, {"id":97,"result":{"thread":{"id":new}}})
        self.bridge._bind_lifecycle_response(96, {"id":96,"result":{"thread":{"id":old}}})
        self.assertEqual(self.bridge._current_thread_id, new)

    def test_first_turn_gate_failure_preserves_valid_native_binding(self):
        thread_id = "0199b724-06b7-7000-8000-000000000014"
        self.send("thread/start", {"fixtureThreadId":thread_id}, 80)
        self.receive()
        original = self.gate.begin
        self.gate.begin = lambda *args, **kwargs: (_ for _ in ()).throw(RuntimeError("fixture"))
        self.send("turn/start", {"input":[{"type":"text","text":"Fails"}]}, 81)
        self.assertIn("error", self.receive())
        self.gate.begin = original
        self.send("turn/start", {"input":[{"type":"text","text":"Retry"}]}, 82)
        while self.receive().get("method") != "turn/completed":
            pass
        self.assertEqual(self.gate.calls, [(thread_id, "Retry", "codex")])

    def test_delegate_locks_model_and_collaboration_settings(self):
        self.gate.decision = "DELEGATE"
        self.send("turn/start", {"threadId":"thread-1","input":[{"type":"text","text":"Fix bug"}],
                                 "model":"unapproved", "effort":"ultra",
                                 "collaborationMode":{"mode":"default","settings":{"model":"other","reasoning_effort":"ultra"}}})
        actual = self.receive()["result"]["observed"]
        self.assertEqual(actual["model"], "exact/route")
        self.assertEqual(actual["effort"], "low")
        self.assertEqual(actual["responsesapiClientMetadata"]["quattro_plan_id"], "plan-1")
        self.assertEqual(actual["collaborationMode"]["settings"]["model"], "exact/route")
        self.assertEqual(self.receive()["method"], "turn/completed")

    def test_control_plane_model_selection_cannot_bypass_turn_lock(self):
        self.gate.decision = "DELEGATE"
        self.send("thread/settings/update", {"threadId":"thread-1", "model":"unapproved",
                  "effort":"ultra", "approvalPolicy":"never",
                  "sandboxPolicy":{"type":"dangerFullAccess"}}, 8)
        self.assertEqual(self.receive()["result"]["method"], "thread/settings/update")
        self.assertEqual(self.gate.calls, [])
        self.send("turn/start", {"threadId":"thread-1","input":[{"type":"text","text":"Fix bug"}],
                  "model":"unapproved", "effort":"ultra",
                  "collaborationMode":{"mode":"default","settings":{
                      "model":"unapproved","reasoning_effort":"ultra"}}}, 9)
        actual = self.receive()["result"]["observed"]
        self.assertEqual(actual["model"], "exact/route")
        self.assertEqual(actual["effort"], "low")
        self.assertEqual(actual["collaborationMode"]["settings"]["model"], "exact/route")
        self.assertEqual(actual["collaborationMode"]["settings"]["reasoning_effort"], "low")
        self.assertEqual(self.receive()["method"], "turn/completed")

    def test_steering_cannot_bypass_fresh_plan(self):
        self.send("turn/steer", {"threadId":"thread-1","input":[{"type":"text","text":"Other task"}]})
        self.assertIn("error", self.receive())
        self.assertEqual(self.gate.calls, [])

    def test_control_plane_operations_pass_without_a_plan(self):
        methods = (
            "thread/settings/update", "model/list", "permissionProfile/list",
            "config/read", "config/value/write", "config/batchWrite",
            "config/mcpServer/reload", "mcpServerStatus/list",
            "thread/metadata/update", "thread/resume", "thread/start", "thread/fork",
        )
        for request_id, method in enumerate(methods, 10):
            with self.subTest(method=method):
                self.send(method, {"threadId":"thread-1"}, request_id)
                self.assertEqual(self.receive()["result"]["method"], method)
        self.assertEqual(self.gate.calls, [])

    def test_sensitive_direct_skips_history_rpc(self):
        self.gate.sensitive = True
        def forbidden(*args):
            raise AssertionError("sensitive history must not persist")
        self.bridge._rpc = forbidden
        self.send("turn/start", {"threadId":"thread-1","input":[{"type":"text","text":"Synthetic sensitive request"}]})
        while True:
            message = self.receive()
            if message.get("method") == "turn/completed":
                self.assertEqual(message["params"]["turn"]["status"], "completed")
                break

    def test_unsupported_execution_paths_are_closed(self):
        for method in ("thread/queue/add", "thread/compact/start", "review/start",
                       "thread/realtime/start", "thread/shellCommand", "turn/settings/update",
                       "command/exec", "mcpServer/tool/call", "thread/inject_items"):
            self.send(method, {"threadId": "thread-1"})
            self.assertIn("error", self.receive())
        self.assertEqual(self.gate.calls, [])

    def test_unknown_protocol_method_fails_closed(self):
        self.send("thread/futureExecutionShortcut", {"threadId":"thread-1"})
        self.assertEqual(self.receive()["error"]["message"],
                         "Unsupported native Codex protocol operation")
        self.assertEqual(self.gate.calls, [])

    def test_methodless_native_approval_response_passes_through(self):
        self._send_raw(json.dumps({"id":77, "result":{"decision":"accept"}}).encode())
        self.assertEqual(self.receive()["result"]["method"], None)
        self.assertEqual(self.gate.calls, [])

    def test_attachments_are_not_silently_ignored(self):
        self.send("turn/start", {"threadId":"thread-1","input":[{"type":"localImage","path":"/synthetic.png"}]})
        self.assertIn("error", self.receive())
        self.assertEqual(self.gate.calls, [])

    def test_gate_failure_does_not_reach_backend(self):
        def fail(*args, **kwargs):
            raise RuntimeError("synthetic provider diagnostic")
        self.gate.begin = fail
        self.send("turn/start", {"threadId":"thread-1","input":[{"type":"text","text":"Explain"}]})
        result = self.receive()
        self.assertIn("error", result)
        self.assertNotIn("synthetic provider diagnostic", json.dumps(result))

    def test_same_thread_concurrency_is_rejected(self):
        entered, release = threading.Event(), threading.Event()
        original = self.gate.direct
        def direct(turn):
            entered.set()
            release.wait(4)
            return original(turn)
        self.gate.direct = direct
        params = {"threadId":"thread-1","input":[{"type":"text","text":"Explain"}]}
        self.send("turn/start", params)
        self.assertTrue(entered.wait(4))
        self.receive()
        self.receive()
        self.send("turn/start", params, 2)
        self.assertIn("error", self.receive())
        release.set()
        while self.receive().get("method") != "turn/completed":
            pass

    def test_private_history_is_bounded_and_merged_on_resume(self):
        self.bridge.history_root = Path(self.tmp.name) / "history"
        thread_id = "0199b724-06b7-7000-8000-000000000002"
        turn_id = "0199b724-06b7-7000-8000-000000000001"
        wire = {"id":turn_id,"status":"completed","startedAt":10,"completedAt":11,
                "items":[{"type":"agentMessage","id":"answer","text":"Public answer","phase":"final_answer"}]}
        self.bridge._save_history(thread_id, wire, "Public question")
        path = self.bridge.history_root / (thread_id + ".json")
        self.assertEqual(path.stat().st_mode & 0o777, 0o600)
        result = {"thread":{"id":thread_id,"turns":[]}}
        self.bridge._merge_history("thread/resume", {"threadId":thread_id}, result)
        self.assertEqual(result["thread"]["turns"][0]["items"][1]["text"], "Public answer")
        self.send("thread/items/list", {"threadId":thread_id,"turnId":turn_id})
        self.assertEqual(len(self.receive()["result"]["data"]), 2)

    def test_private_history_rejects_path_and_symlink(self):
        self.bridge.history_root = Path(self.tmp.name) / "history"
        self.assertIsNone(self.bridge._history_path("../../outside"))
        self.bridge.history_root.symlink_to(Path(self.tmp.name))
        with self.assertRaises(ValueError):
            self.bridge._history_path("0199b724-06b7-7000-8000-000000000002")

    def test_direct_history_pagination_does_not_duplicate(self):
        self.bridge.history_root = Path(self.tmp.name) / "history"
        thread_id = "0199b724-06b7-7000-8000-000000000002"
        for ident, timestamp in [("0199b724-06b7-7000-8000-000000000001", 25),
                                 ("0199b724-06b7-7000-8000-000000000003", 5)]:
            self.bridge._save_history(thread_id, {"id":ident,"status":"completed","startedAt":timestamp,
                "completedAt":timestamp,"items":[{"type":"agentMessage","id":ident,"text":"Answer"}]}, "Question")
        first = {"data":[{"id":"native","startedAt":20}],"nextCursor":"next"}
        self.bridge._merge_history("thread/turns/list", {"threadId":thread_id}, first)
        self.assertEqual([r["startedAt"] for r in first["data"]], [25,20])
        last = {"data":[{"id":"native-old","startedAt":10}],"nextCursor":None}
        self.bridge._merge_history("thread/turns/list", {"threadId":thread_id,"cursor":"next"}, last)
        self.assertEqual([r["startedAt"] for r in last["data"]], [10,5])

    def test_cancel_direct_prevents_answer_delivery(self):
        entered = threading.Event()
        release = threading.Event()
        def direct(turn):
            entered.set()
            release.wait(4)
            return "Must not display"
        self.gate.direct = direct
        self.send("turn/start", {"threadId":"thread-1","input":[{"type":"text","text":"Explain"}]})
        self.assertTrue(entered.wait(4))
        self.assertIn("result", self.receive())
        self.assertEqual(self.receive()["method"], "turn/started")
        self.send("turn/interrupt", {"threadId":"thread-1", "turnId":"direct-turn"}, 2)
        self.assertEqual(self.receive(), {"id":2,"result":{}})
        release.set()
        self.assertEqual(self.receive()["params"]["turn"]["status"], "interrupted")

    def test_real_gate_cancellation_exception_completes_as_interrupted(self):
        from quattro_agent.turn_gate import TurnGate

        entered, release, finished = threading.Event(), threading.Event(), threading.Event()
        original_begin, original_finish = self.gate.begin, self.gate.finish

        def begin(*args, **kwargs):
            turn = original_begin(*args, **kwargs)
            turn.cancel_event = threading.Event()
            turn.budget = None
            turn.socket = None
            turn.connection = None
            return turn

        def direct(turn):
            entered.set()
            release.wait(4)
            # Exercise the production exception raised after cancel(), rather
            # than a fake direct function returning normally on interruption.
            TurnGate.remaining(self.gate, turn)
            raise AssertionError("cancelled turn must not produce an answer")

        def finish(turn, **kwargs):
            original_finish(turn, **kwargs)
            finished.set()

        self.gate.begin, self.gate.direct, self.gate.finish = begin, direct, finish
        self.gate.cancel = lambda turn: TurnGate.cancel(self.gate, turn)
        self.send("turn/start", {"threadId":"thread-1","input":[{"type":"text","text":"Explain"}]})
        self.assertTrue(entered.wait(4))
        self.assertIn("result", self.receive())
        self.assertEqual(self.receive()["method"], "turn/started")
        self.send("turn/interrupt", {"threadId":"thread-1","turnId":"direct-turn"}, 2)
        self.assertEqual(self.receive(), {"id":2,"result":{}})
        release.set()
        completed = self.receive()
        self.assertEqual(completed["method"], "turn/completed")
        self.assertEqual(completed["params"]["turn"]["status"], "interrupted")
        self.assertIsNone(completed["params"]["turn"]["error"])
        self.assertTrue(finished.wait(2))
        self.assertEqual(self.gate.finished[-1], {
            "status":"interrupted", "tools_used":False, "agent_lifecycle":False,
        })


if __name__ == "__main__":
    unittest.main()
